xendit.api.key-name=smashclub-key
xendit.api.secret-key=xnd_development_xn1dEAn0j7fLtX5Q1zkS4qhG1gFzQRhDKlpQYrcT0VtnNLdUMX99zP9qJOtCTbX
xendit.api.public-key=xnd_public_development_Yp_HpuT9hw2PROmqk_ykFUxpSOw2oR88cnopzRU4juTZ9_4YUK07pYiTp1QMMzO3
xendit.api.use-invoice=y
xendit.url.redirect-success=http://localhost:5173
xendit.url.redirect-failed=https://google.com