email.username = a205520f73decfeec2871ede9bee9b2c5113eac5cb236c7ddae0d2277d17e7ec
email.password = 9c4354e76caadfb080523807d90dda130d09448ebed482d450fd1adb792776f2
email.host = smtp.gmail.com
email.port = 25
email.port.ssl = 465
email.port.tls = 587
email.auth = true
email.starttls.enable = true
email.smtp.socket.factory.class = javax.net.ssl.SSLSocketFactory
email.smtp.timeout = 40