spring.application.name=smashclub

# Remove line 3 - 6 later before deployment
#spring.datasource.url = jdbc:sqlserver://localhost:1433;databaseName=BEB29;trustServerSertificate=true
#spring.datasource.username = sa
#spring.datasource.password = 123456

spring.datasource.url = 151b7fe2e506c17f503ecd4195592832663fe42eaa37ce7e32c71699b5056e16c4933750d266ce5cde08895ad7fd2bfeacbd42d5f144a9ce8212a5e5e6e2d36b54d1030a346f3a2b14dc200d8f40b304
spring.datasource.username = 031a61ac0ccc28ae20fb73a66b53a5b9
spring.datasource.password =  a66b7ef2f967873fd6a1b3bd2306aa37
spring.datasource.driverClassName = com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.dialect = org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.naming.physical-strategy = org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
# Create = Drop -> Create ; Update = Append
spring.jpa.hibernate.ddl-auto = create
spring.jpa.properties.hibernate.default_schema = smashclub
spring.jpa.show-sql = true

spring.request.cache.limit = 1048576
spring.servlet.multipart.max-file-size=3MB
server.tomcat.max-part-count=100

# PASTIKAN INI ADA di application.properties:
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.test-connection=false

# Optional: Untuk skip validation
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000

# Spring profiles: Utk kebutuhan seeder
spring.profiles.active=dev

#JWT
jwt.secret-key=scnoiWZIxDoM0pBo5GCMvmMyFuOCeu9luEW+02u2LtE=
jwt.expiration-hours=24
jwt.refresh-expiration-days=7
jwt.issuer=smashclub-backend
jwt.audience=smashclub-client