spring.application.name=smashclub

# Remove line 3 - 6 later before deployment
#spring.datasource.url = jdbc:sqlserver://sqlserver-juara;databaseName=SMASHCLUB;trustServerSertificate=true
#spring.datasource.username = sa
#spring.datasource.password = P4ssw0rd@2025

spring.datasource.url = 151b7fe2e506c17f503ecd419559283251a1d59e1d373fd4daac9c402ba77eed55a576a2550f2f61edad9916110171bbee3a8a3b4b3f3d08ec29279646bae9f59657fe74da79ec0a69472d6585b4350a34f7bd699755ba609633c3f58d497805
spring.datasource.username = 031a61ac0ccc28ae20fb73a66b53a5b9
spring.datasource.password =  1e1921bda87113da3d94804603b09076
spring.datasource.driverClassName = com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.dialect = org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.naming.physical-strategy = org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
# Create = Drop -> Create ; Update = Append
spring.jpa.hibernate.ddl-auto = create
spring.jpa.properties.hibernate.default_schema = smashclub
spring.jpa.show-sql = true

spring.request.cache.limit = 1048576
spring.servlet.multipart.max-file-size=3MB
server.tomcat.max-part-count=100

# PASTIKAN INI ADA di application.properties:
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.test-connection=false

# Optional: Untuk skip validation
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000

# Spring profiles: Utk kebutuhan seeder
# spring.profiles.active=staging

#JWT
jwt.secret-key=scnoiWZIxDoM0pBo5GCMvmMyFuOCeu9luEW+02u2LtE=
jwt.expiration-hours=24
jwt.refresh-expiration-days=7
jwt.issuer=smashclub-backend
jwt.audience=smashclub-client