email.username = 9c38cfa2e2be91779b6c25e7bc8cc6a731b383fbabb96ab52944a9216eb3250d
email.password = c658fc2fb7383f90ee3dac5e4eebf175b40f7629bb910ca88eedb756804aaf9f
email.host = smtp.gmail.com
email.port = 25
email.port.ssl = 465
email.port.tls = 587
email.auth = true
email.starttls.enable = true
email.smtp.socket.factory.class = javax.net.ssl.SSLSocketFactory
email.smtp.timeout = 40